### PR TITLE
fix algo selection for continue_straight without bearings param

### LINKED ISSUE #702: Bearings property cannot be used on any profile
#### Here's what I did

Requested a route that made use of the bearings API parameter, i.e. 
```
https://api.openrouteservice.org/v2/directions/cycling-mountain

{
	"coordinates": [[8.681495,49.41461],[8.687872,49.420318]],
	"bearings": [[25,30],[90,20]]
}
```

---
#### Here's what I got

An error message saying that headings is not supported
```
{
    "error": {
        "code": 2099,
        "message": "Heading is not (fully) supported for CHGraph. See issue #483"
    },
    "info": {
        "engine": {
            "version": "6.1.0",
            "build_date": "2020-04-27T04:45:15Z"
        },
        "timestamp": 1588226836862
    }
}
```

---
#### Here's what I was expecting

That the routing process takes the preferred bearings into account as has previously been the case 

---
#### Here's what I think could be improved

It seems there has been some change in the logic as previously when bearings was passed the system dropped out of using CH as bearings were not possible with that. Now this is not the case and when bearings are provided it does not fall back. This can be seen by adding the `"preference": "shortest"` parameter which then falls out of CH as shortest does not have the CH graph built

### PR DESCRIPTION
**Pull request by takb**
### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the master branch into my feature branch and all conflicts have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [ ] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #702 .

### Information about the changes
- Reason for change:
title says all

### CODE REVIEW

**Review by rabidllama — CHANGES_REQUESTED** [review]
All looks good and works, but the API request documentation tags need updating if this is being allowed in the driving profiles aswell

File: openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java [hunk 1]
```diff
@@ -178,8 +178,8 @@
     private boolean hasBearings = false;
 
     @ApiModelProperty(name = PARAM_CONTINUE_STRAIGHT,
-            value = "Forces the route to keep going straight at waypoints restricting uturns there even if it would be faster. This setting will work for all profiles except for `driving-*`. " +
-            "CUSTOM_KEYS:{'apiDefault':'true','validWhen':{'ref':'profile','valueNot':['driving-*']}}",
+            value = "Forces the route to keep going straight at waypoints restricting uturns there even if it would be faster." +
+            "CUSTOM_KEYS:{'apiDefault':'true'}",
```
Comment (rabidllama) [inline openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java]: I know this is from before, but is this true? I thought that by default continue straight was disabled as it would force the use of slower algorithms.

**Review by rabidllama — CHANGES_REQUESTED** [review]

File: openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java (hunk 1 above)
Comment (takb) [reply openrouteservice/src/main/java/org/heigit/ors/api/requests/routing/RouteRequest.java]: you're right, the actual default is false, corrected docs

**Review by rabidllama — APPROVED** [review]
