### PR TITLE
fix tag order dependency

### LINKED ISSUE #677: Fix/Refactor WaySurfaceTypeGraphStorageBuilder
The current code to interpret way tags to determine surface type produces in some cases different results for the same set of tags depending on the order these are read. 

As @HendrikLeuschner / @aoles were pointing out, the assignment of waytype ferry is also broken. 

The code is also hard to read and cycles through all tags unnecessarily and should be refactored.

### PR DESCRIPTION
**Pull request by takb**
### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the master branch into my feature branch and all conflicts have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [x] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #677 .

### Information about the changes
- Reason for change:
In cases where a surface tag was present on ways but not recognized (had invalid values) the encoded value would not fall back to the derived value based on the waytype, which lead to indeterminate results depending on the order the tags were processed. Implemented a consistent fallback behavior.

### CODE REVIEW

**Review by sfendrich — APPROVED** [review]
Cool! This fix should also improve graph-building performance.

File: openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java [hunk 1]
```diff
@@ -48,39 +51,26 @@ public GraphExtension init(GraphHopper graphhopper) throws Exception {
...
+		} else if (way.hasTag(TAG_HIGHWAY)) {
+			wayType = WayType.getFromString(way.getTag(TAG_HIGHWAY));
+		} else {
+			return;
+		}
+		waySurfaceDesc.setWayType(wayType);
 
-					if (waySurfaceDesc.getSurfaceType() == 0) {
-						if (wayType == WayType.ROAD ||  wayType == WayType.STATE_ROAD || wayType == WayType.STREET) {
-                            waySurfaceDesc.setSurfaceType((byte) SurfaceType.ASPHALT);
```
Comment (aoles) [inline openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java:71]: The assumed surface type `ASPHALT` is a more specific value than `PAVED` considered as the opposite of `UNPAVED`. I believe that if no `surface` tag is present  we should only stratify between the most general  complementing values `PAVED` and `UNPAVED`. This is backed up by to [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:surface) stating: 
> For roads for motor vehicles there there is normally an assumption that the surface is `surface=paved` unless otherwise stated. Paved in OpenStreetMap is non-specific and may cover sealed, tarmac, asphalt, bitumen. `surface=unpaved` is treated as the opposite of paved.

**Review by aoles — CHANGES_REQUESTED** [review]
Thank you, looks great! Please consider my comment regarding using `SurfaceType.PAVED` instead of `SurfaceType.ASPHALT`.

File: openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java (hunk 1 above)
Comment (aoles) [reply openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java:71]: We will make the switch in a separate PR.

**Review by aoles — APPROVED** [review]
