### PR TITLE
fix: ORS_CONFIG_LOCATION not logging with wrong paths

### LINKED ISSUE #1816: ORS_CONFIG_LOCATION doesn't work with *.yaml files
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I set `ORS_CONFIG_LOCATION` environment value to the value `/home/ors/config/config.yml`.
Even with the DEBUG log level, it isn't used.
It is silently ignored.
After debugging, I've checked that it is due to not having the `json` or `yml` extension.
`.yaml` is a very widespread extension for YAML files.  In fact, I never use `.yml`.

### Proposed solution

Accept also *.yaml or document it isn't allowed.

### Additional context

Version 8.1.0
Using Docker image.
By examining `docker-entrypoint.sh` I 've understood whtat happens.

### Forum Topic Link

_No response_

### PR DESCRIPTION
**Pull request by merydian**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [x] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [x] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [ ] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [x] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [x] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [x] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Closes #1816 .

### Information about the changes
- Key functionality added: When a wrong path is set as ORS_CONFIG_LOCATION, this is now no longer silently ignored, but logged.
- Reason for change: Better logging.

The WAR_CONTAINER test is still failing because `ors.config.location` is set in the `war.Dockerfile`:
https://github.com/GIScience/openrouteservice/blob/a0bc59b9b9eaf4eca6785a9ee56b89def30fa3ae/ors-test-scenarios/src/test/resources/war.Dockerfile#L16

I am yet to figure out how to fix this.

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
- None

### Required changes to ors config (if applicable)
- None

[config]: https://GIScience.github.io/openrouteservice/run-instance/configuration/
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

File: ors-test-scenarios/src/test/java/integrationtests/ConfigEnvironmentTest.java [hunk 1]
```diff
@@ -192,5 +194,35 @@ void testActivateEachProfileWithEnvAndOverwriteDefaultConfig(ContainerInitialize
...
+            container.addEnv("ors.config.location", "");
+
+            try {
+                container.start();
+
+                String logs = container.getLogs();
+                Assertions.assertTrue(logs.contains("ORS config file not found at: nonexistent/ors-config.yaml"));
+
+            } catch (ContainerLaunchException e) {
+
```
Comment (sfendrich) [inline ors-test-scenarios/src/test/java/integrationtests/ConfigEnvironmentTest.java]: If this catch-block is empty on purpose, it should contain a comment explaining why.

**Review by sfendrich — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Please make this branch up-to date with main and address the comment below.

**Review by sfendrich — APPROVED** [review]
LGTM
