### PR TITLE
 Fixes to HeavyVehicleGraphStorageBuilder

### LINKED ISSUE #209: OSM key:access not taken into account in HeavyVehicleGraphStorageBuilder
The following code block doesn't produce anything meaningful because an empty `accessTag`  cannot equal to any of the values `"agricultural"`, `"forestry"` or `"bus"` by definition. 
https://github.com/GIScience/openrouteservice/blob/1156e1d34af87f04da6920df7a9e138468dd6f70/openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java#L202-L209

I believe the condition should read `if (!Helper.isEmpty(accessTag))`.

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have merged the latest version of the development branch into my feature branch and all conflicts have been resolved
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading
- [x] 3. I have documented my code using JDocs tags
- [x] 4. I have removed unecessary commented out code, imports and System.out.println statements
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass
- [x] 6. I have created API tests for any new functionality exposed to the API
- [x] 7. If changes/additions are made to the app.config file, I have added these to the app.config.sample file along with a short description of what it is for, and documented this in the Pull Request (below) 
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue)
- [x] 10. For new features involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors)
- [x] 11. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #209 and #211.

### Information about the changes
- Reason for change: Enable `key:access` values to take effect (#209) and use DRYness to fix broken logic of determining vehicle flags (#211). Because any tag processing was originally performed only in the presence of `key:highway` the conditional check for `hasHighway` has been moved outside the loop iterating over way properties.

### CODE REVIEW

File: openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java [hunk 1]
```diff
@@ -331,6 +246,19 @@ private String getHeavyVehicleValue(String key, String hv, String value)
 		
 		return null;
 	}
+
+	private void setFlagsFromTag (String tag, int flag) {
```
Comment (rabidllama) [inline openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java]: May be worth just adding a small JDocs description as to what this method does so that someone can understand quickly without understanding the bit logical operators.

**Review by rabidllama — CHANGES_REQUESTED** [review]

File: openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java (hunk 1 above)
Comment (aoles) [reply openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java]: Thanks Adam, fixed that!

**Review by rabidllama — APPROVED** [review]
