### PR TITLE
fix handling of invalid extra info requests

### LINKED ISSUE #795: Incomplete extra info returned when using items invalid for profile
#### Here's what I did
Request a route with multiple extra info items chosen, some of which are not valid for the selected profile
https://api.openrouteservice.org/v2/directions/foot-walking/json?api_key=xxx
```json
{
	"preference":"recommended",
	"coordinates":[[9.736805,47.100863],[9.783754,47.078656]],
	"extra_info":["steepness","suitability","surface","waycategory","waytype","tollways","traildifficulty","osmid","roadaccessrestrictions","countryinfo","green","noise"]
}
```
---
#### Here's what I got
Not all valid and chosen extra info items are returned (in the above case only steepness, suitability, surface, waycategory and waytype were returned. 

---
#### Here's what I was expecting
At least the traildifficulty should have been returned. When "invalid" items are removed, the response comes back as expected (all selected extra info items are returned in the respnce:
```json
{
	"preference":"recommended",
	"coordinates":[[9.736805,47.100863],[9.783754,47.078656]],
	"extra_info":["steepness","suitability","surface","waycategory","waytype","traildifficulty","green","noise"]
}
```

---
#### Here's what I think could be improved
The response should always include the extra info items chosen, unless they are not valid for that profile

### PR DESCRIPTION
**Pull request by takb**
### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the master branch into my feature branch and all conflicts have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #795 .

### Information about the changes
- Key functionality added:
Handles invalid extra info requests (missing graph extensions meaning extra info not available for the requested profile) by adding a warning and continuing processing of other extra info requests rather than stopping extra info processing and only logging a useless error message on the server.

### CODE REVIEW

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java [hunk 1]
```diff
@@ -13,8 +13,8 @@
  */
 package org.heigit.ors.routing;
 
+import com.google.common.base.Strings;
```
Comment (rabidllama) [inline openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java]: Wouldn't it be better to use internal Java checks for null and empty string rather than including a google library?

**Review by rabidllama — CHANGES_REQUESTED** [review]
Mostly all good, just a query regarding the use of a google library

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java (hunk 1 above)
Comment (takb) [reply openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java]: replaced all usages of `com.google.common.base.Strings` with a new method in `org.heigit.ors.util.StringUtility`.

**Review by rabidllama — APPROVED** [review]
