### PR TITLE
fix(isochrones): use correct edge filter for snapping

### LINKED ISSUE #1491: Fail to build some isochrone on some profile from a point
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Where did you encounter this issue?

live API, self-hosted instance

### Request URL

https://api.openrouteservice.org/v2/isochrones/cycling-regular

### POST Request Body

```JSON
{"locations":[[2.873519,48.957348]],"range":[1000]}
```

### Response

<details><summary>Response</summary>

```JSON
{"error":{"code":3099,"message":"Unable to build an isochrone map."},"info":{"engine":{"build_date":"2023-07-09T01:31:50Z","version":"7.1.0"},"timestamp":1689023575609}}
```
</details>

### Current behavior

An isochrone isn't build, it's the case for profiles `cycling-regular` and `foot-walking` at least, while `driving-car` is working fine.

This happen on multiple points within a train station, [2.873519,48.957348] being only one exemple.

While i'm unsure if maybe the `driving-car` profile have something like "start from the nerest drivable road", i'm sure it's a bit weird in the present case to be able to build a `driving-car` profile and not an `foot-walking` at least. 

This does not look like the issue when some node/way/relation are missing in the data (i assume) and we're trap in the station like with [1.98569,46.948807]

### Expected behavior

An isochrone is returned for profiles `cycling-regular` and `foot-walking`

### Openrouteservice Version

7.1.0

### Build date

2023-07-09T01:31:50Z

### Graph date

_No response_

### Forum Topic Link

_No response_

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the master branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [ ] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [x] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1491, #1533, and #1560 🌈 

### Information about the changes

Fixes the phenomenon where isochrones could not be computed or the computed isochrone was confined to a small subnetwork inaccessible from the rest of the routing network.

[config]: https://GIScience.github.io/openrouteservice/installation/Configuration.html
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

File: ors-engine/src/main/java/org/heigit/ors/isochrones/GraphEdgeMapFinder.java [hunk 1]
```diff
@@ -114,6 +118,6 @@ private static AccessibilityMap calculateTimeDependentAccessibilityMap(Isochrone
 
     private static Weighting createWeighting(IsochroneSearchParameters parameters, FlagEncoder encoder) {
         return parameters.getRangeType() == TravelRangeType.TIME ? new FastestWeighting(encoder)
-                : new DistanceWeighting(encoder);
+                : new ShortestWeighting(encoder);
     }
```
Comment (sfendrich) [inline ors-engine/src/main/java/org/heigit/ors/isochrones/GraphEdgeMapFinder.java:122]: DistanceWeighting differs from ShortestWeighting wrt. details of how the edge weight and minimum edge weight are computed. Are we sure that replacing DistanceWeighting has no undesired side-effects?

**Review by sfendrich — APPROVED** [review]
LGTM.
