### PR TITLE
fix extra-info processing with alternative_routes algo

### LINKED ISSUE #681: alternative_routes together with extra_info will provide wrong extra_info
#### Here's what I did

request to 
`https://api.openrouteservice.org/v2/directions/driving-car/geojson`
body:
```
{"preference":"fastest","language":"en-US","instructions":true,"geometry":true,"units":"m","attributes":["detourfactor","percentage"],"instructions_format":"html","elevation":true,"coordinates":[[8.507195,48.946406],[8.50771,48.953142]],"alternative_routes":{"target_count":3},"extra_info":["steepness","waytype","surface"]}
```
using alternative_routes and some `extra_info` value.

---
#### Here's what I got

The waypoint number the extra info index refers to (34+) is out of bounds of the coordinates array for the current route (32 points).
grafik

The `extras` response property for each route contain the segments of all 3 routes if the coordinate arrays of all routes would be merged.

---
#### Here's what I was expecting

extras objects should only contain the segments of the route they are placed in.

---
#### Here's what I think could be improved
Tests for newly implemented parameters that also cover using the new parameter with existing parameters.

### PR DESCRIPTION
**Pull request by takb**
### Pull Request Checklist

- [x] 1. I have [**rebased**](https://github.com/GIScience/openrouteservice/blob/master/CONTRIBUTE.md#pull-request-guidelines) the latest version of the master branch into my feature branch and all conflicts have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the app.config file, I have added these to the app.config wiki page on github along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset (at least Germany) and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the importer etc.), I have generated longer distance routes for the affected profiles with different options (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end points generated from the current live ORS. If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage and why the change was needed.

Fixes #681 .

### Information about the changes
fixes grouping issue for extra info with alternative_routes algo.

### CODE REVIEW

**Comment by takb** [comment]
see also https://github.com/GIScience/graphhopper/releases/tag/v0.13.4

File: openrouteservice-api-tests/src/test/java/org/heigit/ors/services/routing/ResultTest.java [hunk 1]
```diff
@@ -764,7 +764,7 @@ public void testExtrasDetails() {
 				.when().log().ifValidationFails()
 				.get(getEndPointName());
 
-		response.then()
+		response.then().log().all()
```
Comment (rabidllama) [inline openrouteservice-api-tests/src/test/java/org/heigit/ors/services/routing/ResultTest.java]: Probably better here to only log if the validation fails to save cluttering up the output of tests

File: openrouteservice-api-tests/src/test/java/org/heigit/ors/v2/services/routing/ResultTest.java [hunk 2]
```diff
@@ -2785,28 +2785,33 @@ public void testAlternativeRoutes() {
...
+        body.put("extra_info", getParameter("extra_info"));
         given()
             .header("Accept", "application/json")
             .header("Content-Type", "application/json")
             .pathParam("profile", getParameter("carProfile"))
             .body(body.toString())
             .when()
             .post(getEndPointPath() + "/{profile}")
-            .then()
+            .then().log().all()
```
Comment (rabidllama) [inline openrouteservice-api-tests/src/test/java/org/heigit/ors/v2/services/routing/ResultTest.java]: again, better to just log if the validation fails

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java [hunk 3]
```diff
@@ -409,26 +411,49 @@ public RouteResult matchTrack(MapMatchingRequest req) throws Exception {
                 }
             }
 
-            try {
-                for (Object obj : gr.getReturnObjects()) {
-                    if (obj instanceof ExtraInfoProcessor) {
-                        if (extraInfoProcessor == null) {
-                            extraInfoProcessor = (ExtraInfoProcessor)obj;
+            List<ExtraInfoProcessor> extraList = new ArrayList<>();
+            for (Object o : gr.getReturnObjects()) {
```
Comment (rabidllama) [inline openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java]: It would be clearer to use a more informative variable name here (and for the others later) such as `returnObject`

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java [hunk 4]
```diff
@@ -325,7 +325,9 @@ public RouteResult matchTrack(MapMatchingRequest req) throws Exception {
             throw new InternalServerException(RoutingErrorCodes.INVALID_PARAMETER_VALUE, "Alternative routes algorithm does not support more than two way points.");
         }
 
-        ExtraInfoProcessor extraInfoProcessor = null;
+        int numberOfExpectedExtraInfoProcessors = req.getSearchParameters().getAlternativeRoutesCount();
```
Comment (rabidllama) [inline openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java]: Could these two lines be combined/made a bit easier to read?

File: openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java [hunk 5]
```diff
@@ -230,8 +230,20 @@ else if (ALT_ROUTE.equalsIgnoreCase(algoStr))
 			EdgeFilter edgeFilter = edgeFilterFactory.createEdgeFilter(request.getAdditionalHints(), encoder, getGraphHopperStorage());
 			routingTemplate.setEdgeFilter(edgeFilter);
 
-			PathProcessor pathProcessor = pathProcessorFactory.createPathProcessor(request.getAdditionalHints(), encoder, getGraphHopperStorage());
-			ghRsp.addReturnObject(pathProcessor);
+
+			if (request.getAlgorithm().equals("alternative_route")) {
+				for (int c = 0; c < request.getHints().getInt("alternative_route.max_paths", 2); c++) {
```
Comment (rabidllama) [inline openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java]: so this loop adds the same response object depending on the number of alternative routes requested? Is there a clearer way of writing this as at first glance it looks like there is something not quite right...

**Review by rabidllama — CHANGES_REQUESTED** [review]
Just a couple of things that could be made a little clearer in the code

File: openrouteservice-api-tests/src/test/java/org/heigit/ors/services/routing/ResultTest.java (hunk 1 above)
Comment (takb) [reply openrouteservice-api-tests/src/test/java/org/heigit/ors/services/routing/ResultTest.java]: forgot to remove the line...

File: openrouteservice-api-tests/src/test/java/org/heigit/ors/v2/services/routing/ResultTest.java (hunk 2 above)
Comment (takb) [reply openrouteservice-api-tests/src/test/java/org/heigit/ors/v2/services/routing/ResultTest.java]: ditto

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java (hunk 4 above)
Comment (takb) [reply openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java]: i don't really know if it made it easier to read...

File: openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java (hunk 5 above)
Comment (takb) [reply openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java]: I had the more concise version before and thought that would make it easier to read and understand, but ok...

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java [hunk 6]
```diff
@@ -325,7 +325,8 @@ public RouteResult matchTrack(MapMatchingRequest req) throws Exception {
             throw new InternalServerException(RoutingErrorCodes.INVALID_PARAMETER_VALUE, "Alternative routes algorithm does not support more than two way points.");
         }
 
-        ExtraInfoProcessor extraInfoProcessor = null;
+        int numberOfExpectedExtraInfoProcessors = req.getSearchParameters().getAlternativeRoutesCount() < 0 ? 1 : req.getSearchParameters().getAlternativeRoutesCount();
+        ExtraInfoProcessor[] extraInfoProcessor = new ExtraInfoProcessor[numberOfExpectedExtraInfoProcessors];
```
Comment (sfendrich) [inline openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java]: Would `extraInfoProcessors` be a better name for this variable?

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java [hunk 7]
```diff
@@ -409,26 +410,49 @@ public RouteResult matchTrack(MapMatchingRequest req) throws Exception {
...
+
+            if (numberOfExpectedExtraInfoProcessors > 1) {
+                int extraInfoProcessorIndex = 0;
+                for (Object o : gr.getReturnObjects()) {
+                    if (o instanceof ExtraInfoProcessor) {
+                        extraInfoProcessor[extraInfoProcessorIndex] = (ExtraInfoProcessor)o;
+                        extraInfoProcessorIndex++;
+                    }
+                }
+            } else {
```
Comment (sfendrich) [inline openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java:421]: Why is it necessary to distinguish between more-than-one and one-or-less expected extraInfoProcessors?

Comment (takb) [reply openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java:421]: because multiple EIPs could mean two different things: either multiple paths are separate routes with an EIP each, or they are segments of one route and the EIPs need to be concatenated.

File: openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java (hunk 6 above)
Comment (takb) [reply openrouteservice/src/main/java/org/heigit/ors/routing/RoutingProfileManager.java]: yep.

**Review by sfendrich — APPROVED** [review]

**Review by rabidllama — APPROVED** [review]
