### PR TITLE
fix: correct surface information for routes involving sidewalks

### LINKED ISSUE #2067: ORS returns wrong surface type for sidewalks
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Way https://www.openstreetmap.org/way/314456049 is tagged with `sidewalk=right` and `sidewalk:right:surface=paving_stones` but routing with the walking profile returns asphalt as surface-type in the extra-infos:
https://classic-maps.openrouteservice.org/directions?n1=49.006985&n2=8.394571&n3=18&a=49.008105,8.394751,49.005874,8.394382&b=2&c=0&k1=en-US&k2=km

### Proposed solution

For pedestrian profiles extra infos tagged for the sidewalk should take precedence of the extra infos for the way.

### Additional context

_No response_

### Forum Topic Link

_No response_

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #2067.
 
### Information about the changes
- Key functionality added: Process sidewalks attached to ways via `sidewalk = *` OSM tags into separate graph edges of `WayType.FOOTWAY` and take into account their surface as defined by `sidewalk:surface` or `sidewalk:*:surface` tags.

- Reason for change: Incorrect way type and surface returned in extra info in case of pedestrian routes that go along streets which have sidewalks attached to the OSM way representing the street.

### Examples and reasons for differences between live ORS routes, and those generated from this pull request

The original example from the issue **before** ...

image

... and **after** applying the the changes in this PR:

image

[config]: https://GIScience.github.io/openrouteservice/run-instance/configuration/
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java [hunk 1]
```diff
@@ -17,21 +17,34 @@
 import com.graphhopper.reader.ReaderWay;
 import com.graphhopper.storage.GraphExtension;
 import com.graphhopper.util.EdgeIteratorState;
+import lombok.Getter;
```
Comment (sfendrich) [inline ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java:20]: Isn't lombok overkill for just one setter and one getter?

**Review by sfendrich — APPROVED** [review]
lgtm, thank you!

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java (hunk 1 above)
Comment (aoles) [reply ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/WaySurfaceTypeGraphStorageBuilder.java:20]: In this case it might appear so. However, since we use lombok in the project anyway I would argue it makes sense to use it for any trivial getter and setter instead of implementing it.
