### PR TITLE
fix: avoid roads reserved to customers

### LINKED ISSUE #1981: Directions API routes through parking lots rather than go through intersections
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

For the record I first posted about this issue on the forum ([link](https://ask.openrouteservice.org/t/problematic-routing-from-ors/7089)) but I figured it made more sense to create an issue here. This issue will more or less be a copy paste of that forum post.
<br>

Basically, when using the Directions API (self-hosted through Docker), sometimes the route returned by ORS takes ‘shortcuts’ through parking lots (and other similar type "roads"), instead of going through the proper intersections.
This is an issue since, unless I am mistaken, where I live this is illegal to do. Its also typically much slower due to the much lower speed limit in parking lots + the presence of pedestrians. Also, it results in an overall higher number of turns compared to using the ‘normal’ intersection…

I first saw this issue on a self hosted (Docker) ORS instance. I tried on 3 computers (1 Linux, two Windows, all through Docker so the host OS should not have any impact regarding this issue), with the latest OSM data for the region (Canada/Québec).

I then tried and got the same result with ORS’s online map service. Here are some simple examples of what can happen:
[Example 1](https://classic-maps.openrouteservice.org/directions?n1=45.645151&n2=-73.860172&n3=18&a=45.645818,-73.858595,45.644663,-73.862629&b=0&c=0&k1=en-US&k2=km)
[Example 2](https://classic-maps.openrouteservice.org/directions?n1=45.644719&n2=-73.859426&n3=18&a=45.645818,-73.858595,45.644341,-73.86154&b=0&c=0&k1=en-US&k2=km)
[Example 3](https://classic-maps.openrouteservice.org/directions?n1=45.645203&n2=-73.868294&n3=18&a=45.645796,-73.869088,45.644693,-73.869361&b=0&c=0&k1=en-US&k2=km)
[Example 4](https://classic-maps.openrouteservice.org/directions?n1=45.643898&n2=-73.869045&n3=18&a=45.644802,-73.868964,45.643399,-73.870059&b=0&c=0&k1=en-US&k2=km)

In all those cases, the proposed route is worst then simply following the ‘real’ road due to traversing parking lots.

Now, for the record, I tried those very same examples on OpenStreetMap’s website using all three available routing engines (Valhalla, GraphHopper, OSRM) and they all gave a ‘normal’ result that uses the intersection, as expected.

<br>

My best guess as to why this is happening is that those roads are marked with the OSM tag “highway=service” (or at least the ones I checked) but without the “service=parking_aisle". Some of the ones I tested had “service=driveway”. From what I can tell, they all had “access=customer”.

From my understanding of the OSM tags documentation, all of those should have been avoided, unless absolutely needed (like if the start/end point was only accessible through such road).

<br>

I also tried to find some settings in the API or within the different driving profiles, but I haven’t found anything that allowed me to avoid such results.

Am I doing something wrong? Did I truly find a bug, and if so, where should I start looking to try and fix this (if I figure out how to that is)?
I haven't really coded in Java in a while but i might be able to look into it a little.

<br>
<br>

PS: Sorry, this is so long, I tried to give all the details I could think of… But i figured its probably better to give more than less.

<br>
<br>

Also, just to be clear, it does not do that on every corner with parking lots and/or businesses/shops. I did find some that do work properly like this one here:
[Properly working corner example](https://classic-maps.openrouteservice.org/directions?n1=45.643771&n2=-73.858868&n3=18&a=45.643336,-73.858461,45.644521,-73.859217&b=0&c=0&k1=en-US&k2=km)

And here is a somewhat ironic case where it tries very very hard to avoid going through the parking lot, even though it starts from within that very same parking lot:
[Peculiar routing](https://classic-maps.openrouteservice.org/directions?n1=45.639896&n2=-73.842764&n3=18&a=45.640016,-73.842491,45.640316,-73.843516&b=0&c=0&k1=en-US&k2=km)
I still included it as it might be linked to this issue somehow?

Also, there was this issue that seemed somewhat similar to mine : [GitHub Issue](https://github.com/GIScience/openrouteservice/issues/339)

### Proposed solution

I dont have the necessary knowledge to be able to propose an actual solution, but i suspect it will probably be related to the way ORS handles OSM's tags and the weighs used when calculating routes?

### Additional context

_No response_

### Forum Topic Link

https://ask.openrouteservice.org/t/problematic-routing-from-ors/7089

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [ ] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1981.

### Information about the changes
- Key functionality added: Introduce a weight penalty on roads tagged with `access = customers` in order to avoid them during route calculation.
- Reason for change:  sometimes the route returned by ORS takes "shortcuts" through parking lots, gas stations, or similar instead of following the regular road. This is of an issue because it:
  - might be illegal to do
  - is typically much slower due to the lower speed limit and  the presence of pedestrians
  - results in an overall higher number of turns compared to the direct route.

### Examples and reasons for differences between live ORS routes, and those generated from this pull request

The following examples from the original issue now yield the desired routes.

image

image

image

image

[config]: https://GIScience.github.io/openrouteservice/run-instance/configuration/
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java [hunk 1]
```diff
@@ -52,7 +58,9 @@ public LimitedAccessWeighting(Weighting superWeighting, PMap map) {
         destinationPenalty = checkBounds("road_access_destination_factor", map.getDouble("road_access_destination_factor", defaultDestinationFactor), MIN_DESTINATION_FACTOR, MAX_DESTINATION_FACTOR);
         double defaultPrivateFactor = encoder.getTransportationMode().isMotorVehicle() ? VEHICLE_PRIVATE_FACTOR : DEFAULT_PRIVATE_FACTOR;
         privatePenalty = checkBounds("road_access_private_factor", map.getDouble("road_access_private_factor", defaultPrivateFactor), MIN_PRIVATE_FACTOR, MAX_PRIVATE_FACTOR);
-        roadAccessEnc = destinationPenalty > 1 || privatePenalty > 1 ? encoder.getEnumEncodedValue(RoadAccess.KEY, RoadAccess.class) : null;
+        double defaultCustomersFactor = encoder.getTransportationMode().isMotorVehicle() ? VEHICLE_CUSTOMERS_FACTOR : DEFAULT_CUSTOMERS_FACTOR;
+        customersPenalty = checkBounds("road_access_customers_factor", map.getDouble("road_access_customers_factor", defaultCustomersFactor), MIN_CUSTOMERS_FACTOR, MAX_CUSTOMERS_FACTOR);
```
[the remark this answers is not in the document]
Comment (aoles) [reply ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java]: None of the `road_access_*` factors is currently subject to configuration.

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java [hunk 2]
```diff
@@ -27,19 +27,25 @@
...
  */
 public class LimitedAccessWeighting extends AbstractAdjustedWeighting {
-    public static double DEFAULT_DESTINATION_FACTOR = 1;
-    public static double VEHICLE_DESTINATION_FACTOR = 10;
-    public static double DEFAULT_PRIVATE_FACTOR = 1.2;
-    public static double VEHICLE_PRIVATE_FACTOR = 10;
+    public static final double DEFAULT_DESTINATION_FACTOR = 1;
+    public static final double VEHICLE_DESTINATION_FACTOR = 10;
+    public static final double DEFAULT_PRIVATE_FACTOR = 1.2;
+    public static final double VEHICLE_PRIVATE_FACTOR = 10;
```
[the remark this answers is not in the document]
Comment (aoles) [reply ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java:35]: No need to do so as the names and code is self-explanatory.

File: CHANGELOG.md [hunk 3]
```diff
@@ -40,6 +40,7 @@ Releasing is documented in RELEASE.md
 ### Removed
 
 ### Fixed
+- avoid routing on roads with access reserved to customers ([#2060](https://github.com/GIScience/openrouteservice/pull/2060))
```
Comment (sfendrich) [inline CHANGELOG.md:45]: Usually, we use the issue-id instead of the PR-id in the changelog.

File: .github/workflows/vulnerability-scanning.yml
Comment (sfendrich) [inline .github/workflows/vulnerability-scanning.yml:1]: How are the changes of these file related to the PR?

File: ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java [hunk 4]
```diff
@@ -4579,6 +4579,45 @@ void testBarriersAccessPermit() {
...
+        given()
+                .headers(CommonHeaders.jsonContent)
+                .pathParam("profile", getParameter("carProfile"))
+                .body(body.toString())
+                .when()
+                .post(getEndPointPath() + "/{profile}")
+                .then()
+                .assertThat()
+                .body("any { it.key == 'routes' }", is(true))
+                .body("routes[0].summary.distance", is(35.6f))
```
Comment (sfendrich) [inline ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java]: floating point values schould be compared with error margin.

File: ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java [hunk 5]
```diff
@@ -4579,6 +4579,45 @@ void testBarriersAccessPermit() {
...
+        given()
+                .headers(CommonHeaders.jsonContent)
+                .pathParam("profile", getParameter("carProfile"))
+                .body(body.toString())
+                .when()
+                .post(getEndPointPath() + "/{profile}")
+                .then()
+                .assertThat()
+                .body("any { it.key == 'routes' }", is(true))
+                .body("routes[0].summary.distance", is(60.3f))
```
Comment (sfendrich) [inline ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java]: floating point values should be compared with error margin

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java [hunk 6]
```diff
@@ -27,32 +27,38 @@
...
-    static double MIN_PRIVATE_FACTOR = 1;
-    static double MAX_PRIVATE_FACTOR = 10;
+    public static final double MIN_FACTOR = 1;// ensure that we do not need to change getMinWeight, i.e. road_access_factor >= 1
+    public static final double MAX_FACTOR = 10;
+    public static final double DEFAULT_DESTINATION_FACTOR = 1;
+    public static final double VEHICLE_DESTINATION_FACTOR = 10;
+    public static final double DEFAULT_PRIVATE_FACTOR = 1.2;
+    public static final double VEHICLE_PRIVATE_FACTOR = 10;
+    public static final double DEFAULT_CUSTOMERS_FACTOR = 1.2;
+    public static final double VEHICLE_CUSTOMERS_FACTOR = 1.5;
```
Comment (sfendrich) [inline ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java:37]: Shouldn't this be treated with similar values as access:destination?

**Review by sfendrich — CHANGES_REQUESTED** [review]
Just a few minor comments.

File: CHANGELOG.md (hunk 3 above)
Comment (aoles) [reply CHANGELOG.md:45]: Actually, I've seen both. While usually it doesn't make much of a difference, it still can happen that:
- although a PR fixes or implements the functionality described in an issue it actually goes beyond that description such that it is necessary to read through the PR's description in order to comprehend it fully 
- there is no corresponding issue to a PR
- a single PR tackles multiple issues

Therefore, I personally prefer to include the PR-id. Please note that PR ids is also what ends up in the auto-generated release notes.

File: .github/workflows/vulnerability-scanning.yml
Comment (aoles) [reply .github/workflows/vulnerability-scanning.yml:1]: Fair point 👍  I had to make these adjustments in order for the actions to run through, as they started failing for reasons seemingly unrelated to the contents of this PR.

Do you want me to open a separate PR addressing only the issues with the GitHub actions?

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java (hunk 6 above)
Comment (aoles) [reply ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/weighting/LimitedAccessWeighting.java:37]: Not necessarily. If you set the factor as high as for `access = destination`, you start observing issues such as on reported in the original issue:

> And here is a somewhat ironic case where it tries very very hard to avoid going through the parking lot, even though it starts from within that very same parking lot:
[Peculiar routing](https://classic-maps.openrouteservice.org/directions?n1=45.639896&n2=-73.842764&n3=18&a=45.640016,-73.842491,45.640316,-73.843516&b=0&c=0&k1=en-US&k2=km)

In fact, it might make sense to loosen up the factors for destination a bit, but this is not the scope of this PR. I've played around with the factors and found that 1.5 already produces good results, while setting it too high might cause weird detours. As an example, consider the route to the gas station:

image

Once the factor is increased to 10 (the same as for destination) you get:

image

File: .github/workflows/vulnerability-scanning.yml
Comment (aoles) [reply .github/workflows/vulnerability-scanning.yml:1]: In fact, you can see these actions failing now on main after some recent merge.

Comment (sfendrich) [reply .github/workflows/vulnerability-scanning.yml:1]: O.K., then lets leave it in this PR

File: CHANGELOG.md (hunk 3 above)
Comment (sfendrich) [reply CHANGELOG.md:45]: ok.

File: ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java (hunk 4 above)
Comment (aoles) [reply ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java]: Thanks for pointing this out! I've fixed it.

File: ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java (hunk 5 above)
Comment (aoles) [reply ors-api/src/test/java/org/heigit/ors/apitests/routing/ResultTest.java]: Thanks for pointing this out! I've fixed it.

**Review by sfendrich — APPROVED** [review]
LGTM
