### PR TITLE
fix: elevation set to false not taken into account

### LINKED ISSUE #1967: `elevation: false` not taken into account
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Documentation suggest that setting `elevation: false` in any `*.build` config section disables elevation.
It seems though as if elevation tiles still get downloaded, which shouldn't happen.

### Proposed solution

`elevation: false` shouldn't download elevation tiles.

### Additional context

_No response_

### Forum Topic Link

https://ask.openrouteservice.org/t/cannot-disable-elevation/6969/2

### PR DESCRIPTION
**Pull request by merydian**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [x] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [x] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [x] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [x] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [x] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1967 .

### Information about the changes
- Key functionality added:
- Reason for change:

### Examples and reasons for differences between live ORS routes, and those generated from this pull request
-

### Required changes to ors config (if applicable)
-

[config]: https://GIScience.github.io/openrouteservice/run-instance/configuration/
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java [hunk 1]
```diff
@@ -26,6 +26,7 @@ public class ORSGraphHopperConfig extends GraphHopperConfig {
     private List<CHProfile> coreProfiles = new ArrayList<>();
     private List<LMProfile> coreLMProfiles = new ArrayList<>();
     private List<Profile> fastisochroneProfiles = new ArrayList<>();
+    private static final org.apache.log4j.Logger LOGGER = org.apache.log4j.Logger.getLogger(ORSGraphHopperConfig.class.getName());
```
Comment (MichaelsJP) [inline ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java]: This is a fully qualified import. Better to import the library directly at the top with the others.

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java [hunk 2]
```diff
@@ -39,7 +40,18 @@ public static ORSGraphHopperConfig createGHSettings(ProfileProperties profile, E
...
+            LOGGER.warn("Elevation is set to false.");
+        }
+        if (elevationProps.getProvider() == null) {
+            LOGGER.warn("Elevation provider is null.");
+        }
+        if (elevationProps.getCachePath() == null) {
+            LOGGER.warn("Elevation cache path is null.");
+        }
+
+        if (profile.getBuild().getElevation() && elevationProps.getProvider() != null && elevationProps.getCachePath() != null) {
```
Comment (MichaelsJP) [inline ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java]: Add a variable e.g. boolean addElevation = true;
If any of the follwing if statements hits, switch it to false and print a warning.
The if clause in line 54 would then just be a single if(addElevation) ...

File: ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+        EngineProperties engineConfig = new EngineProperties();
+        engineConfig.setGraphsDataAccess(DataAccessEnum.MMAP);
+        engineConfig.getElevation().setCachePath(Path.of("/elevation_cache"));
+        engineConfig.getElevation().setDataAccess(DataAccessEnum.MMAP);
+
+        String graphLocation = "";
+
+        ORSGraphHopperConfig config = ORSGraphHopperConfig.createGHSettings(profile, engineConfig, graphLocation);
+
+        assert !config.toString().contains("graph.elevation.provider");
```
Comment (MichaelsJP) [inline ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java]: Better to use the junit native assertion library: import static org.junit.jupiter.api.Assertions.assertTrue; etc.

File: ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+        engineConfig.setGraphsDataAccess(DataAccessEnum.MMAP);
+        engineConfig.getElevation().setCachePath(Path.of("/elevation_cache"));
+        engineConfig.getElevation().setProvider("srtm");
+        engineConfig.getElevation().setDataAccess(DataAccessEnum.MMAP);
+
+        String graphLocation = "";
+
+        ORSGraphHopperConfig config = ORSGraphHopperConfig.createGHSettings(profile, engineConfig, graphLocation);
+
+        assert config.toString().contains("graph.elevation.provider");
```
Comment (MichaelsJP) [inline ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java]: See above.

File: ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+        engineConfig.setGraphsDataAccess(DataAccessEnum.MMAP);
+        engineConfig.getElevation().setCachePath(null);
+        engineConfig.getElevation().setProvider("srtm");
+        engineConfig.getElevation().setDataAccess(DataAccessEnum.MMAP);
+
+        String graphLocation = "";
+
+        ORSGraphHopperConfig config = ORSGraphHopperConfig.createGHSettings(profile, engineConfig, graphLocation);
+
+        assert !config.toString().contains("graph.elevation.provider");
```
Comment (MichaelsJP) [inline ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java]: See above.

File: ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+        engineConfig.setGraphsDataAccess(DataAccessEnum.MMAP);
+        engineConfig.getElevation().setCachePath(Path.of("/elevation_cache"));
+        engineConfig.getElevation().setProvider(null);
+        engineConfig.getElevation().setDataAccess(DataAccessEnum.MMAP);
+
+        String graphLocation = "";
+
+        ORSGraphHopperConfig config = ORSGraphHopperConfig.createGHSettings(profile, engineConfig, graphLocation);
+
+        assert !config.toString().contains("graph.elevation.provider");
```
Comment (MichaelsJP) [inline ors-engine/src/test/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfigTest.java]: See above.

**Review by MichaelsJP — CHANGES_REQUESTED** [review]
A few minor things.

Please revise the sonarcloud issues and the comments below :arrow_down:

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java [hunk 7]
```diff
@@ -39,7 +42,24 @@ public static ORSGraphHopperConfig createGHSettings(ProfileProperties profile, E
...
+            }
+            if (elevationProps.getProvider() == null) {
+                LOGGER.warn("Elevation provider is null.");
+            }
+            if (elevationProps.getCachePath() == null) {
+                LOGGER.warn("Elevation cache path is null.");
+            }
+        }
+
+        if (Boolean.TRUE.equals(addElevation)) {
```
Comment (MichaelsJP) [inline ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopperConfig.java]:
```suggestion
        boolean addElevation = true;

    
        if (!profile.getBuild().getElevation()) {
            LOGGER.warn("Elevation is set to false.");
            addElevation = false;
        }
        if (elevationProps.getProvider() == null) {
            LOGGER.warn("Elevation provider is null.");
            addElevation = false;
        }
        if (elevationProps.getCachePath() == null) {
            LOGGER.warn("Elevation cache path is null.");
            addElevation = false;
        }
        
        if (!addElevation) {
             LOGGER.warn("Elevation deactivated.");
        } else {
```

**Review by MichaelsJP — CHANGES_REQUESTED** [review]
Just a last minor thing. 
The best is to encapsulate if-conditions as little as possible. See the corrected code above.

**Review by MichaelsJP — APPROVED** [review]
LGTM
