### PR TITLE
fix: correctly resolve access to ways tagged with `hgv=delivery`

### LINKED ISSUE #1743: `hgv=delivery`-tags not considered properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Where did you encounter this issue?

live API

### Request URL

https://api.openrouteservice.org/v2/pdirections/driving-hgv/geojson

### POST Request Body

```JSON
{
"preference":"recommended",
"geometry":true,
"options":{"vehicle_type":"delivery"},
"coordinates":[[10.857732,48.415395],[10.893041,48.369262]]
}
```

### Response

<details><summary>Response</summary>

```JSON

{"error":{"code":2009,"message":"Route could not be found - Unable to find a route between points 1 (10.8577320 48.4153950) and 2 (10.8930410 48.3692620)."},"info":{"engine":{"build_date":"2024-01-29T14:41:12Z","version":"7.1.1"},"timestamp":1710158524932}}

```
</details>

### Current behavior

The whole inner city of Augsburg is tagged with `hgv:delivery`.
Currently, a regular  `hgv` vehicle (no vehicle type) is able to enter the city, but a vehicle with vehicle type `delivery` is not.

### Expected behavior

A regular `hgv` vehicle (no vehicle type) should not be able to enter the city, but a vehicle with vehicle type `delivery` should be.

### Openrouteservice Version

7.1.1

### Build date

2024-01-29T14:41:12Z

### Graph date

_No response_

### Forum Topic Link

_No response_

### PR DESCRIPTION
**Pull request by aoles**
### Pull Request Checklist

- [x] 1. I have [**rebased**][rebase] the latest version of the main branch into my feature branch and all conflicts
         have been resolved.
- [x] 2. I have added information about the change/addition to functionality to the CHANGELOG.md file under the
         [Unreleased] heading.
- [ ] 3. I have documented my code using JDocs tags.
- [x] 4. I have removed unnecessary commented out code, imports and System.out.println statements.
- [ ] 5. I have written JUnit tests for any new methods/classes and ensured that they pass.
- [x] 6. I have created API tests for any new functionality exposed to the API.
- [ ] 7. If changes/additions are made to the ors-config.json file, I have added these to the [ors config documentation][config]
         along with a short description of what it is for, and documented this in the Pull Request (below).
- [x] 8. I have built graphs with my code of the Heidelberg.osm.gz file and run the api-tests with all test passing
- [x] 9. I have referenced the Issue Number in the Pull Request (if the changes were from an issue).
- [ ] 10. For new features or changes involving building of graphs, I have tested on a larger dataset
          (at least Germany), and the graphs build without problems (i.e. no out-of-memory errors).
- [ ] 11. For new features or changes involving the graphbuilding process (i.e. changing encoders, updating the
          importer etc.), I have generated longer distance routes for the affected profiles with different options
          (avoid features, max weight etc.) and compared these with the routes of the same parameters and start/end
          points generated from the current live ORS.
          If there are differences then the reasoning for these **MUST** be documented in the pull request.
- [x] 12. I have written in the Pull Request information about the changes made including their intended usage
          and why the change was needed.
- [ ] 13. For changes touching the API documentation, I have tested that the API playground [renders correctly][api].

Fixes #1743.

### Information about the changes
- Key functionality added: routing on ways tagged as `hgv=delivery` is allowed for vehicle type `delivery` but not for `hgv`.
- Reason for change: ways with `hgv=delivery` tag were blocked for vehicle type `delivery` but accessible to `hgv`.

[config]: https://GIScience.github.io/openrouteservice/run-instance/configuration/
[api]: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-docs-api#test-new-ors-documentation
[rebase]: https://github.com/GIScience/openrouteservice/blob/main/CONTRIBUTE.md#pull-request-guidelines

### CODE REVIEW

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java [hunk 1]
```diff
@@ -179,22 +178,13 @@ public void processWay(ReaderWay way) {
                 }
 
                 if (motorVehicleHgvValues.contains(key)) {
-
-                    // TODO: the following implementation does not pick up access:destination
```
Comment (koebi) [inline ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java:183]: Is `access=destination` picked up by the new implementation? 
If not, I think we should keep the comment?

**Review by koebi — CHANGES_REQUESTED** [review]
One small note, other than that it looks good :)

Edit: I did check with the request mentioned in the Issue and can confirm that the fix does what it should :)

File: ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java (hunk 1 above)
Comment (koebi) [reply ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java:183]: According to @aoles, access destination appears there only because a few years ago there was some idea to address the routing on access destination edges through this edge filter, but this never worked properly.

**Comment by koebi** [comment]
As discussed, @aoles will add some tests for this tagging scenario.

**Comment by aoles** [comment]
Thanks @koebi for reviewing the PR ❤️ I've added the test, should be fine to go forward with the merge. Cheers!

**Review by koebi — APPROVED** [review]
